import { BookOpenCheck, Brain, CircleAlert, FileCheck2, Link2 } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { WorkspaceCard } from "@/components/director-workspace/workspace-card";
import type { TimelineIntegrityProjection as TimelineIntegrityMetric } from "@/features/enterprise-projections";

const stateVariant = { Healthy: "success", Watch: "warning", Attention: "error" } as const;

export function TimelineIntegrityPanel({ items }: { items: TimelineIntegrityMetric[] }) {
  return <WorkspaceCard title="Timeline integrity" description="Whether enterprise history is attributable, connected, and ready for executive navigation." action={<CircleAlert className="size-5 text-warning" aria-hidden="true" />}><ul className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{items.map((item) => <li key={item.label} className="rounded-lg border border-border p-3"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold text-fg">{item.label}</p><p className="mt-2 text-lg font-semibold text-fg tabular-nums">{item.value}</p></div><Badge variant={stateVariant[item.state]}>{item.state}</Badge></div><p className="mt-2 text-[0.7rem] leading-4 text-fg-secondary">{item.detail}</p></li>)}</ul></WorkspaceCard>;
}

export function RecentTimelineContext({ decisions, knowledge, prompts }: { decisions: readonly { id: string; title: string; state: string; relationship: string }[]; knowledge: readonly { title: string; source: string; change: string }[]; prompts: readonly string[] }) {
  return <div className="grid gap-5 xl:grid-cols-3"><WorkspaceCard title="Recent decisions" description="Conceptual Decision Center projection." action={<FileCheck2 className="size-5 text-primary" aria-hidden="true" />}><ul className="divide-y divide-border">{decisions.map((item) => <li key={item.id} className="py-3 first:pt-0 last:pb-0"><div className="flex items-center justify-between gap-3"><p className="text-sm font-semibold text-fg">{item.title}</p><Badge variant="warning">{item.state}</Badge></div><p className="mt-1 text-xs text-primary">{item.id}</p><p className="mt-1 text-[0.7rem] leading-4 text-fg-secondary">{item.relationship}</p></li>)}</ul></WorkspaceCard><WorkspaceCard title="Knowledge changes" description="Conceptual Knowledge Domain projection." action={<BookOpenCheck className="size-5 text-primary" aria-hidden="true" />}><ul className="divide-y divide-border">{knowledge.map((item) => <li key={item.title} className="py-3 first:pt-0 last:pb-0"><p className="text-sm font-semibold text-fg">{item.title}</p><p className="mt-1 text-xs text-primary">{item.source}</p><p className="mt-1 text-[0.7rem] text-fg-secondary">{item.change}</p></li>)}</ul></WorkspaceCard><WorkspaceCard title="Heby timeline context" description="Simulated advisory prompts. Heby cannot act or change enterprise history." action={<Badge variant="info">Advisory only</Badge>}><div className="flex items-center gap-2 text-xs text-fg-secondary"><Brain className="size-4 text-primary" aria-hidden="true" />Timeline-aware conversation starters</div><ul className="mt-3 space-y-2">{prompts.map((prompt) => <li key={prompt}><button type="button" disabled className="flex min-h-10 w-full cursor-not-allowed items-center justify-between rounded-lg border border-border bg-surface-sunken/40 px-3 text-left text-xs font-medium text-fg opacity-80"><span>{prompt}</span><Link2 className="size-3.5 shrink-0 text-primary" aria-hidden="true" /></button></li>)}</ul><p className="mt-3 text-[0.7rem] leading-4 text-fg-muted">Simulation only · Director authority remains final</p></WorkspaceCard></div>;
}
