"use client";

/*
 * revision-generation-evidence.tsx — the Knowledge evidence supplied to generation of the ONE
 * revision under review (KT-2), shown inside the existing review control.
 *
 * It is not a second review surface: it decides nothing and records nothing. It asks the server for
 * the evidence recorded with the message that generated these bytes, and renders that record — or
 * the exact reason there is none — under a notice that says what the evidence does NOT prove.
 *
 * Loaded on request, so opening a History does not read every revision's evidence unasked.
 */
import { useState, useTransition } from "react";
import { readRevisionGenerationEvidenceAction } from "@/app/(dashboard)/operations/actions";
import {
  REVISION_EVIDENCE_NON_CLAIMS,
  GROUNDING_CHECK_NOTICE,
  GROUNDING_CHECK_NOT_RUN,
  GROUNDING_CHECK_VERDICT,
  REVISION_EVIDENCE_NOTICE,
  boundedUniverseSelectionSentence,
  groundingClaimLabel,
  type RevisionEvidenceItem,
  type RevisionGenerationEvidence as Evidence,
} from "@/features/heby-answer/revision-generation-evidence";

/** Why there is no evidence list, in words. One sentence per closed answer. */
function absence(evidence: Exclude<Evidence, { status: "recorded" }>): string {
  switch (evidence.status) {
    case "unauthorized":
      return "Sign in to see the evidence supplied to this revision's generation.";
    case "revision-unresolvable":
      return "This revision could not be resolved in this organization, so no evidence is shown.";
    case "unavailable":
      return "The generation record could not be read. Nothing is shown rather than an incomplete or guessed list.";
    case "no-generation-message":
      return `Revision ${evidence.revisionNo} was not generated by Hebun, so no evidence was supplied to a generation.`;
    case "no-retrieval-recorded":
      return `Revision ${evidence.revisionNo} was generated, but no Knowledge retrieval was recorded with it.`;
  }
}

/** The recorded selection, in words. Zero items is said plainly, never left as an empty box. */
function selectionSentence(evidence: Extract<Evidence, { status: "recorded" }>): string {
  const { selection, items } = evidence;
  if (selection.status === "bounded-universe") return boundedUniverseSelectionSentence(items.length, evidence.revisionNo);
  if (items.length > 0) {
    return `Retrieval supplied ${items.length} Knowledge record${items.length === 1 ? "" : "s"} to the generation of revision ${evidence.revisionNo}.`;
  }
  const why =
    selection.status === "no-match"
      ? "no Knowledge record matched"
      : selection.status === "empty-corpus"
        ? "the organization held no Knowledge"
        : selection.status === "empty-query"
          ? "the request carried nothing searchable"
          : selection.status === "unavailable"
            ? `Knowledge could not be read${selection.unavailableReason ? ` (${selection.unavailableReason})` : ""}`
            : `retrieval ended as "${selection.status}"`;
  return `No Knowledge evidence was selected for revision ${evidence.revisionNo}: ${why}.`;
}

function ItemRow({ item }: { item: RevisionEvidenceItem }) {
  return (
    <li className="rounded border border-border-subtle p-2">
      <p className="text-xs font-medium text-fg-primary">
        {item.title} <span className="font-normal text-fg-muted">· {item.domainKey}/{item.factKey}</span>
      </p>
      <p className="text-xs text-fg-muted">
        version {item.knowledgeVersion} · {item.ratifiedAtGeneration ? "ratified when supplied" : "not ratified when supplied"}
        {item.authorityClass ? ` · ${item.authorityClass}` : ""}
        {item.lifecycleStatus ? ` · ${item.lifecycleStatus}` : ""} · scope {item.scope}
      </p>
      {item.excerpt ? (
        <p className="mt-1 whitespace-pre-wrap text-xs text-fg-secondary">
          {item.excerpt}
          {item.excerptTruncated ? " … (shortened when recorded)" : ""}
        </p>
      ) : (
        <p className="mt-1 text-xs text-fg-muted">No statement text was recorded with this record.</p>
      )}
    </li>
  );
}

/** GS-1 — the advisory grounding check for the recorded evidence above. Decides nothing. */
function GroundingCheck({ grounding }: { grounding: Extract<Evidence, { status: "recorded" }>["grounding"] }) {
  return (
    <div className="mt-2 border-t border-border-subtle pt-2" data-grounding-check={grounding.status}>
      <p className="text-xs text-fg-secondary">{GROUNDING_CHECK_NOTICE}</p>
      <p className="mt-1 text-xs text-fg-primary">{GROUNDING_CHECK_VERDICT[grounding.status]}</p>
      {grounding.claims.length > 0 ? (
        <ul className="mt-1 flex flex-col gap-1 text-xs text-fg-muted">
          {grounding.claims.map((claim, i) => (
            <li key={i} data-grounding-claim={claim.support.status}>
              &ldquo;{claim.text}&rdquo; — {groundingClaimLabel(claim.support)}
            </li>
          ))}
        </ul>
      ) : null}
    </div>
  );
}

export function RevisionGenerationEvidence({
  artifactId,
  revisionId,
}: {
  artifactId: string;
  revisionId: string;
}) {
  const [pending, startTransition] = useTransition();
  const [evidence, setEvidence] = useState<Evidence | null>(null);
  const [open, setOpen] = useState(false);

  function toggle() {
    if (open) {
      setOpen(false);
      return;
    }
    setOpen(true);
    if (evidence) return;
    startTransition(async () => {
      try {
        setEvidence(await readRevisionGenerationEvidenceAction({ artifactId, revisionId }));
      } catch {
        setEvidence({ status: "unavailable", reason: "provenance-unreadable" });
      }
    });
  }

  return (
    <div className="mt-2">
      <button
        type="button"
        onClick={toggle}
        aria-expanded={open}
        className="text-xs text-fg-secondary underline-offset-2 hover:text-fg-primary hover:underline"
      >
        {open ? "Hide evidence supplied to generation" : "Show evidence supplied to generation"}
      </button>
      {open ? (
        <div className="mt-1 rounded border border-border-subtle p-2">
          <p className="text-xs text-fg-secondary">{REVISION_EVIDENCE_NOTICE}</p>
          <ul className="mt-1 list-disc pl-4 text-xs text-fg-muted">
            {REVISION_EVIDENCE_NON_CLAIMS.map((claim) => (
              <li key={claim}>{claim}</li>
            ))}
          </ul>
          {pending || !evidence ? (
            <p className="mt-2 text-xs text-fg-muted">Reading the generation record…</p>
          ) : evidence.status === "recorded" ? (
            <>
              <p className="mt-2 text-xs text-fg-primary">{selectionSentence(evidence)}</p>
              {evidence.selection.degradedReason ? (
                <p className="text-xs text-fg-muted">Retrieval note recorded: {evidence.selection.degradedReason}</p>
              ) : null}
              {evidence.items.length > 0 ? (
                <ul className="mt-2 flex flex-col gap-2">
                  {evidence.items.map((item) => (
                    <ItemRow key={`${item.domainKey}/${item.factKey}/${item.knowledgeVersion}`} item={item} />
                  ))}
                </ul>
              ) : null}
              <GroundingCheck grounding={evidence.grounding} />
            </>
          ) : (
            <>
              <p className="mt-2 text-xs text-fg-primary">{absence(evidence)}</p>
              <p className="mt-1 text-xs text-fg-muted" data-grounding-check="not-run">{GROUNDING_CHECK_NOT_RUN}</p>
            </>
          )}
        </div>
      ) : null}
    </div>
  );
}
