"use client";

import { useMemo, useState } from "react";
import { ArrowRight, ChevronDown, RotateCcw } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import type { Decision, DecisionDateRange, DecisionFilterState, DecisionImpact, DecisionPriority, DecisionRisk, DecisionStatus } from "@/features/decision-domain/mock";

const statusOptions: Array<DecisionStatus | "All statuses"> = ["All statuses", "Waiting Review", "Evidence Required", "Deferred", "Approved", "Rejected"];
const priorityOptions: Array<DecisionPriority | "All priorities"> = ["All priorities", "Critical", "High", "Medium", "Low"];
const impactOptions: Array<DecisionImpact | "All impacts"> = ["All impacts", "Transformational", "High", "Medium", "Low"];
const riskOptions: Array<DecisionRisk | "All risks"> = ["All risks", "Critical", "High", "Medium", "Low"];
const attentionOptions: DecisionFilterState["attention"][] = ["Any attention", "Director attention", "No attention required"];
const dateOptions: DecisionDateRange[] = ["All dates", "Due today", "Due this week", "No deadline"];
const initialFilters: DecisionFilterState = { status: "All statuses", priority: "All priorities", impact: "All impacts", risk: "All risks", domain: "All domains", owner: "All owners", requestedBy: "All requesters", attention: "Any attention", date: "All dates" };
const priorityVariant = { Critical: "error", High: "warning", Medium: "info", Low: "neutral" } as const;
const statusVariant = { "Waiting Review": "warning", "Evidence Required": "error", Deferred: "neutral", Approved: "success", Rejected: "error" } as const;
const riskVariant = { Critical: "error", High: "warning", Medium: "info", Low: "neutral" } as const;

function DecisionSelect({ id, label, value, options, onChange }: { id: string; label: string; value: string; options: string[]; onChange: (value: string) => void }) {
  return <label htmlFor={id} className="block"><span className="mb-1 block text-[0.65rem] font-semibold uppercase tracking-wider text-fg-muted">{label}</span><span className="relative block"><select id={id} value={value} onChange={(event) => onChange(event.target.value)} className="min-h-10 w-full appearance-none rounded-lg border border-border bg-surface px-3 pr-8 text-xs text-fg outline-none transition-colors focus-visible:border-primary focus-visible:ring-2 focus-visible:ring-primary-ring/30"><option value={options[0]}>{options[0]}</option>{options.slice(1).map((option) => <option key={option} value={option}>{option}</option>)}</select><ChevronDown className="pointer-events-none absolute right-2.5 top-3 size-4 text-fg-muted" aria-hidden="true" /></span></label>;
}

export function DecisionWorkspace({ items }: { items: Decision[] }) {
  const [filters, setFilters] = useState<DecisionFilterState>(initialFilters);
  const [localStatuses, setLocalStatuses] = useState<Record<string, DecisionStatus>>({});
  const [announcement, setAnnouncement] = useState("No local review action recorded.");
  const domains = useMemo(() => ["All domains", ...Array.from(new Set(items.flatMap((item) => item.domains)))], [items]);
  const owners = useMemo(() => ["All owners", ...Array.from(new Set(items.map((item) => item.owner.name)))], [items]);
  const requesters = useMemo(() => ["All requesters", ...Array.from(new Set(items.map((item) => item.requestedBy)))], [items]);
  const filtered = useMemo(() => items.filter((item) => { const status = localStatuses[item.id] ?? item.status; return (filters.status === "All statuses" || status === filters.status) && (filters.priority === "All priorities" || item.priority === filters.priority) && (filters.impact === "All impacts" || item.impact === filters.impact) && (filters.risk === "All risks" || item.risk === filters.risk) && (filters.domain === "All domains" || item.domains.includes(filters.domain)) && (filters.owner === "All owners" || item.owner.name === filters.owner) && (filters.requestedBy === "All requesters" || item.requestedBy === filters.requestedBy) && (filters.attention === "Any attention" || (filters.attention === "Director attention" ? item.directorAttention : !item.directorAttention)) && (filters.date === "All dates" || item.dateRange === filters.date); }), [filters, items, localStatuses]);
  const recordReview = (decision: Decision, status: DecisionStatus) => { setLocalStatuses((current) => ({ ...current, [decision.id]: status })); setAnnouncement(`${decision.id} locally marked ${status}. Nothing was persisted or executed.`); };

  return <section aria-labelledby="decision-workspace-title" className="rounded-xl border border-border bg-surface"><div className="border-b border-border p-4 sm:p-5"><div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div><h2 id="decision-workspace-title" className="text-base font-semibold text-fg">Decision workspace</h2><p className="mt-1 text-sm text-fg-secondary">Review priority, evidence, risk, impact, ownership, and follow-up before recording Director intent.</p></div><Badge variant="primary">{filtered.length} of {items.length} decisions</Badge></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-9">
    <DecisionSelect id="decision-status" label="Status" value={filters.status} options={statusOptions} onChange={(value) => setFilters((current) => ({ ...current, status: statusOptions.find((option) => option === value) ?? "All statuses" }))} />
    <DecisionSelect id="decision-priority" label="Priority" value={filters.priority} options={priorityOptions} onChange={(value) => setFilters((current) => ({ ...current, priority: priorityOptions.find((option) => option === value) ?? "All priorities" }))} />
    <DecisionSelect id="decision-impact" label="Impact" value={filters.impact} options={impactOptions} onChange={(value) => setFilters((current) => ({ ...current, impact: impactOptions.find((option) => option === value) ?? "All impacts" }))} />
    <DecisionSelect id="decision-risk" label="Risk" value={filters.risk} options={riskOptions} onChange={(value) => setFilters((current) => ({ ...current, risk: riskOptions.find((option) => option === value) ?? "All risks" }))} />
    <DecisionSelect id="decision-domain" label="Domain" value={filters.domain} options={domains} onChange={(value) => setFilters((current) => ({ ...current, domain: domains.find((option) => option === value) ?? "All domains" }))} />
    <DecisionSelect id="decision-owner" label="Owner" value={filters.owner} options={owners} onChange={(value) => setFilters((current) => ({ ...current, owner: owners.find((option) => option === value) ?? "All owners" }))} />
    <DecisionSelect id="decision-requester" label="Requested by" value={filters.requestedBy} options={requesters} onChange={(value) => setFilters((current) => ({ ...current, requestedBy: requesters.find((option) => option === value) ?? "All requesters" }))} />
    <DecisionSelect id="decision-attention" label="Attention" value={filters.attention} options={attentionOptions} onChange={(value) => setFilters((current) => ({ ...current, attention: attentionOptions.find((option) => option === value) ?? "Any attention" }))} />
    <DecisionSelect id="decision-date" label="Date" value={filters.date} options={dateOptions} onChange={(value) => setFilters((current) => ({ ...current, date: dateOptions.find((option) => option === value) ?? "All dates" }))} />
  </div><button type="button" onClick={() => setFilters(initialFilters)} className="mt-3 inline-flex min-h-9 items-center gap-2 rounded-lg px-2 text-xs font-semibold text-primary transition-colors hover:bg-primary-subtle focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary-ring"><RotateCcw className="size-3.5" aria-hidden="true" />Reset filters</button><p className="sr-only" aria-live="polite">{announcement}</p></div>
  {filtered.length ? <ol className="divide-y divide-border">{filtered.map((decision) => { const status = localStatuses[decision.id] ?? decision.status; return <li key={decision.id} className="p-4 sm:p-5"><details className="group"><summary className="cursor-pointer list-none rounded-lg focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-primary-ring"><div className="grid gap-4 xl:grid-cols-[minmax(17rem,1.4fr)_minmax(14rem,0.8fr)_auto] xl:items-center"><div><div className="flex flex-wrap items-center gap-2"><Badge variant={priorityVariant[decision.priority]}>{decision.priority}</Badge><Badge variant="neutral">{decision.category}</Badge>{decision.directorAttention ? <Badge variant="error">Director attention</Badge> : <span className="text-[0.65rem] font-semibold uppercase tracking-wider text-fg-muted">No attention required</span>}</div><h3 className="mt-2 text-sm font-semibold text-fg">{decision.title}</h3><p className="mt-1 text-xs leading-5 text-fg-secondary">{decision.summary}</p><p className="mt-2 text-[0.7rem] text-fg-muted">{decision.id} · Due {decision.dueDate}</p></div><dl className="grid grid-cols-2 gap-2 text-xs"><div><dt className="text-fg-muted">Owner</dt><dd className="mt-1 font-medium text-fg">{decision.owner.name}</dd></div><div><dt className="text-fg-muted">Requested by</dt><dd className="mt-1 font-medium text-fg">{decision.requestedBy}</dd></div><div><dt className="text-fg-muted">Confidence</dt><dd className="mt-1 font-medium text-fg tabular-nums">{decision.confidence}%</dd></div><div><dt className="text-fg-muted">Decision date</dt><dd className="mt-1 font-medium text-fg">{decision.decisionDate}</dd></div></dl><div className="flex flex-wrap items-center gap-2 xl:justify-end"><Badge variant={riskVariant[decision.risk]}>{decision.risk} risk</Badge><Badge variant={statusVariant[status]}>{status}</Badge><span className="flex items-center gap-1 text-xs font-semibold text-primary">Inspect <ChevronDown className="size-3.5 transition-transform group-open:rotate-180" aria-hidden="true" /></span></div></div></summary>
    <div className="mt-5 grid gap-5 border-t border-border pt-5 xl:grid-cols-[minmax(0,1.2fr)_minmax(20rem,0.8fr)]"><div className="space-y-5"><div><h4 className="text-xs font-semibold uppercase tracking-wider text-fg-muted">Full explanation</h4><p className="mt-2 text-sm leading-6 text-fg-secondary">{decision.explanation}</p></div><div><h4 className="text-xs font-semibold uppercase tracking-wider text-fg-muted">Supporting evidence</h4><ul className="mt-2 space-y-2">{decision.evidence.map((evidence) => <li key={evidence.title} className="rounded-lg border border-border bg-surface-sunken/35 p-3"><div className="flex items-start justify-between gap-3"><p className="text-xs font-semibold text-fg">{evidence.title}</p><Badge variant={evidence.trust === "Verified" ? "success" : evidence.trust === "Reviewed" ? "info" : "warning"}>{evidence.trust}</Badge></div><p className="mt-1 text-[0.7rem] text-primary">{evidence.source}</p><p className="mt-1 text-xs leading-5 text-fg-secondary">{evidence.summary}</p></li>)}</ul></div><div><h4 className="text-xs font-semibold uppercase tracking-wider text-fg-muted">Conceptual relationships</h4><ul className="mt-2 grid gap-2 sm:grid-cols-2">{decision.relationships.map((relationship) => <li key={`${relationship.kind}-${relationship.label}`} className="rounded-lg border border-border p-3"><p className="text-[0.65rem] font-semibold uppercase tracking-wider text-primary">{relationship.kind}</p><p className="mt-1 text-xs font-semibold text-fg">{relationship.label}</p><p className="mt-1 flex items-center gap-1 text-[0.7rem] text-fg-secondary"><ArrowRight className="size-3" aria-hidden="true" />{relationship.relationship}</p></li>)}</ul><p className="mt-2 text-[0.7rem] text-fg-muted">Conceptual projections only · no graph or Runtime resolution</p></div></div>
    <div><dl className="space-y-3 text-xs"><div><dt className="font-semibold text-fg-muted">Expected impact</dt><dd className="mt-1 leading-5 text-fg">{decision.expectedImpact}</dd></div><div><dt className="font-semibold text-fg-muted">Affected domains</dt><dd className="mt-1 text-fg">{decision.domains.join(" · ")}</dd></div><div><dt className="font-semibold text-fg-muted">Risks</dt><dd className="mt-1 text-fg">{decision.risks.join(" · ")}</dd></div><div><dt className="font-semibold text-fg-muted">Alternatives</dt><dd className="mt-1 text-fg">{decision.alternatives.join(" · ")}</dd></div><div><dt className="font-semibold text-fg-muted">Organization</dt><dd className="mt-1 text-fg">{decision.relatedOrganization.join(" · ")}</dd></div><div><dt className="font-semibold text-fg-muted">Knowledge</dt><dd className="mt-1 text-fg">{decision.relatedKnowledge.join(" · ")}</dd></div><div><dt className="font-semibold text-fg-muted">Timeline events</dt><dd className="mt-1 text-fg">{decision.relatedTimeline.join(" · ")}</dd></div><div><dt className="font-semibold text-fg-muted">Policies</dt><dd className="mt-1 text-fg">{decision.relatedPolicies.join(" · ")}</dd></div><div><dt className="font-semibold text-fg-muted">Follow-up recommendations</dt><dd className="mt-1 text-fg">{decision.followUp.join(" · ")}</dd></div></dl><div className="mt-5 border-t border-border pt-4"><p className="text-[0.7rem] leading-4 text-fg-muted">Local review simulation only. These controls do not persist, execute, approve workflows, or change enterprise systems.</p><div className="mt-3 flex flex-wrap gap-2"><button type="button" onClick={() => recordReview(decision, "Approved")} className="min-h-10 rounded-lg bg-success px-4 text-xs font-semibold text-white focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary-ring">Approve</button><button type="button" onClick={() => recordReview(decision, "Rejected")} className="min-h-10 rounded-lg bg-error px-4 text-xs font-semibold text-white focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary-ring">Reject</button><button type="button" onClick={() => recordReview(decision, "Deferred")} className="min-h-10 rounded-lg border border-border px-4 text-xs font-semibold text-fg focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary-ring">Defer</button></div></div></div></div>
    </details></li>; })}</ol> : <div className="p-10 text-center"><p className="text-sm font-semibold text-fg">No decisions match these filters.</p><p className="mt-1 text-xs text-fg-secondary">Reset or broaden the local filter selection.</p></div>}</section>;
}
