import { ArrowRight, BrainCircuit, CircleAlert, Link2, Network } from "lucide-react";
import Link from "next/link";
import { Badge } from "@/components/ui/badge";
import { WorkspaceCard } from "@/components/director-workspace/workspace-card";
import type { CrossDomainContext, EnterpriseIntelligenceMetric, EnterpriseIntelligenceSignal, IntelligenceState, UnifiedHealthItem } from "@/features/enterprise-intelligence/mock";

const stateVariant = { Healthy: "success", Watch: "warning", Attention: "error" } as const;

function StateBadge({ state }: { state: IntelligenceState }) {
  return <Badge variant={stateVariant[state]}>{state}</Badge>;
}

export function EnterpriseIntelligenceOverview({ items, overall }: { items: EnterpriseIntelligenceMetric[]; overall: { label: string; value: string; detail: string; state: IntelligenceState } }) {
  return <section aria-labelledby="enterprise-intelligence-overview-title" className="rounded-xl border border-primary/20 bg-surface p-5 shadow-sm"><div className="flex flex-col gap-4 border-b border-border pb-5 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary">Integrated enterprise context</p><h1 id="enterprise-intelligence-overview-title" className="mt-2 text-2xl font-semibold tracking-tight text-fg">Enterprise Intelligence Overview</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-fg-secondary">Organization, Knowledge, Timeline, and Decisions remain independent while contributing to one executive understanding.</p></div><div className="min-w-0 rounded-lg border border-error/20 bg-error-subtle/50 p-3 sm:max-w-xs"><div className="flex items-center justify-between gap-3"><p className="text-xs font-semibold text-fg">{overall.label}</p><StateBadge state={overall.state} /></div><p className="mt-2 text-lg font-semibold text-fg">{overall.value}</p><p className="mt-1 text-xs leading-5 text-fg-secondary">{overall.detail}</p></div></div><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-4">{items.map((item) => <article key={item.domain} className="flex min-w-0 flex-col rounded-lg border border-border bg-surface-sunken/35 p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-[0.65rem] font-semibold uppercase tracking-wider text-primary">{item.domain}</p><h2 className="mt-1 text-sm font-semibold text-fg">{item.label}</h2></div><StateBadge state={item.state} /></div><p className="mt-3 text-2xl font-semibold tabular-nums text-fg">{item.value}</p><p className="mt-1 text-xs text-fg-secondary">{item.detail}</p><p className="mt-3 flex-1 border-t border-border pt-3 text-[0.7rem] leading-5 text-fg-muted"><Link2 className="mr-1 inline size-3 text-primary" aria-hidden="true" />{item.relationship}</p><Link href={item.href} className="mt-3 inline-flex min-h-9 items-center gap-1 text-xs font-semibold text-primary focus-visible:rounded focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary-ring">Review {item.domain}<ArrowRight className="size-3.5" aria-hidden="true" /></Link></article>)}</div></section>;
}

export function ExecutiveIntelligenceSignals({ items }: { items: EnterpriseIntelligenceSignal[] }) {
  return <WorkspaceCard title="Executive intelligence signals" description="Explanatory cross-domain indicators. No AI reasoning, prediction, or execution." action={<CircleAlert className="size-5 text-primary" aria-hidden="true" />}><ul className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{items.map((item) => <li key={item.label} className="rounded-lg border border-border p-3"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold text-fg">{item.label}</p><p className="mt-1 text-xl font-semibold tabular-nums text-fg">{item.value}</p></div><StateBadge state={item.state} /></div><p className="mt-2 text-xs leading-5 text-fg-secondary">{item.explanation}</p><p className="mt-2 text-[0.65rem] font-medium text-primary">{item.domains.join(" · ")}</p></li>)}</ul></WorkspaceCard>;
}

export function CrossDomainContextPanel({ items }: { items: CrossDomainContext[] }) {
  const stages = ["Organization", "Knowledge", "Timeline", "Decision"] as const;
  return <WorkspaceCard title="Cross-domain executive context" description="Connected explanations, not graph navigation. Each Domain retains its own ownership." action={<Network className="size-5 text-primary" aria-hidden="true" />}><div className="mb-4 flex flex-wrap items-center gap-2 rounded-lg border border-primary/15 bg-primary-subtle/40 px-3 py-2 text-xs font-semibold text-fg">{[...stages, "Heby"].map((stage, index) => <span key={stage} className="flex items-center gap-2"><span>{stage}</span>{index < stages.length ? <ArrowRight className="size-3.5 text-primary" aria-hidden="true" /> : null}</span>)}</div><ul className="grid gap-4 xl:grid-cols-3">{items.map((item) => { const contextRows = [["Organization", item.organization], ["Knowledge", item.knowledge], ["Timeline", item.timeline], ["Decision", item.decision]]; return <li key={item.title} className="rounded-lg border border-border p-4"><h3 className="text-sm font-semibold text-fg">{item.title}</h3><dl className="mt-3 space-y-2">{contextRows.map(([stage, value]) => <div key={stage} className="grid grid-cols-[5.5rem_minmax(0,1fr)] gap-2 text-xs"><dt className="font-semibold text-primary">{stage}</dt><dd className="leading-5 text-fg-secondary">{value}</dd></div>)}</dl><p className="mt-3 border-t border-border pt-3 text-xs font-medium leading-5 text-fg">{item.outcome}</p></li>; })}</ul><p className="mt-4 text-[0.7rem] text-fg-muted">Conceptual projection only · no graph engine, retrieval, reasoning, or shared Domain ownership</p></WorkspaceCard>;
}

export function UnifiedEnterpriseHealth({ items }: { items: UnifiedHealthItem[] }) {
  return <WorkspaceCard title="Unified Enterprise Health" description="Health emerges from relationships across Domains, not isolated percentages." action={<BrainCircuit className="size-5 text-primary" aria-hidden="true" />}><ul className="divide-y divide-border">{items.map((item) => <li key={item.domain} className="grid gap-3 py-4 first:pt-0 last:pb-0 md:grid-cols-[10rem_5rem_minmax(0,1fr)] md:items-center"><div><p className="text-sm font-semibold text-fg">{item.domain}</p><StateBadge state={item.state} /></div><p className="text-xl font-semibold tabular-nums text-fg">{item.value}</p><div><p className="text-xs leading-5 text-fg-secondary">{item.contribution}</p><p className="mt-1 text-[0.7rem] font-medium text-primary">{item.relationship}</p></div></li>)}</ul></WorkspaceCard>;
}
