/*
 * media-assets/external-generative-data-use.ts — MAY THESE BYTES BE SENT TO THIS EXTERNAL GENERATIVE
 * PROVIDER, FOR THIS PURPOSE? (DATA-USE-MEDIA-GUARD-1)
 *
 * PURE. No I/O, no clock. The lineage it is given is read by `external-generative-eligibility.server.ts`
 * from the Media authority's own provenance; the decision is made here, against a closed list.
 *
 * ── WHY THIS EXISTS ──────────────────────────────────────────────────────────
 *
 * Before this phase, "is this image eligible as the input of an external generation?" was answered by
 * CUSTODY alone (admitted, an image, this tenant's, bytes intact). Custody says Hebun holds the bytes.
 * It says nothing about whether the organization's photographs may be handed to a third-party model
 * whose terms may let it train on them. A provider switch being on says nothing about it either.
 *
 *     CUSTODY              != DATA-USE PERMISSION
 *     REVIEW ACCEPTED      != DATA-USE PERMISSION
 *     SELECTED / PACKAGED  != DATA-USE PERMISSION
 *     PROVIDER SWITCH ON   != DATA-USE PERMISSION
 *     GOVERNANCE APPROVAL  != DATA-USE PERMISSION
 *
 * None of those facts is an input here, on purpose.
 *
 * ── WHAT IS DECIDED, AND ON WHAT ─────────────────────────────────────────────
 *
 *   provider   the resolved transport's own provider name — never a caller string
 *   purpose    the processing class: `reference-edit` (MEDIA-5) or `image-to-video` (IMAGE → VIDEO)
 *   lineage    whether ANY asset in the source's lineage was SUPPLIED by a human (Drive), or the
 *              whole lineage is Hebun-generated — walked through derivations and generation sources,
 *              so a generated image made FROM a supplied photograph is not laundered into "generated"
 *
 * ── THE DECISION IS CLOSED, AND UNKNOWN IS NOT ALLOWED ───────────────────────
 *
 * `allowed` only when a RECORDED decision below names this exact provider, purpose and lineage class.
 * Everything else is `unknown`, and `unknown` refuses exactly as `denied` does. An unreadable lineage is
 * `unknown`. There is no default-allow and no wildcard.
 *
 * Every row cites the Director evidence that makes it true. A row is a policy decision, so adding or
 * changing one is a reviewed code change — the same way the capability→scope map is. This list is
 * NOT per-tenant: no tenant-scoped data-use policy exists in the repository, and inventing one here
 * would be a second policy authority without a Director decision. When a tenant needs its own grant
 * (an enterprise agreement with a provider, say), that is a durable authority of its own.
 *
 * ── WHAT IS DELIBERATELY NOT RECORDED ────────────────────────────────────────
 *
 *   - Supplied media → OpenAI reference edit. Never decided. MEDIA-5's surface already withholds the
 *     control for a supplied asset ("a separate Director decision"); now the authority does too.
 *   - Anything → Higgsfield image-to-video. Director G2 (2026-09-27): real company/customer images are
 *     NOT authorized while Higgsfield's Terms §4.4 training question is open. Provenance cannot tell a
 *     synthetic supplied PNG from a real product photograph (the IMAGE → VIDEO acceptance source was a
 *     synthetic image admitted as `supplied`), and no decision covers generated sources, so the whole
 *     path is `unknown`. That is a missing decision, not a verdict on the provider.
 *
 * Publishing to the organization's own Instagram / YouTube is not external generative processing and
 * never reaches this module.
 */

/** The processing classes that send an admitted asset's bytes to an external generative model. */
export const EXTERNAL_GENERATIVE_PURPOSES = ["reference-edit", "image-to-video"] as const;
export type ExternalGenerativePurpose = (typeof EXTERNAL_GENERATIVE_PURPOSES)[number];

/**
 * The lineage class of a source asset. `includes-supplied` when any asset reachable through derivation
 * or generation source is human-supplied; `generated-only` when every one of them was generated by
 * Hebun from a prompt alone at the root.
 */
export type SourceLineageClass = "generated-only" | "includes-supplied";

export type SourceLineage =
  | { readonly status: "resolved"; readonly lineage: SourceLineageClass }
  | { readonly status: "unresolvable" };

export type DataUseDecision = "allowed" | "denied" | "unknown";

export interface RecordedDataUseDecision {
  readonly provider: string;
  readonly purpose: ExternalGenerativePurpose;
  readonly lineage: SourceLineageClass;
  readonly decision: Exclude<DataUseDecision, "unknown">;
  /** Where the Director decided it. A row without evidence does not belong here. */
  readonly evidence: string;
}

/**
 * THE RECORDED DECISIONS. One row today.
 *
 * MEDIA-5 was production-accepted by the Director (release 0fd1dc67, repair 8bd177cf) by sending a
 * MEDIA-2B GENERATED asset (8494e3ad) to OpenAI's `/v1/images/edits`. That is the one combination
 * a Director decision covers.
 */
export const RECORDED_DATA_USE_DECISIONS: readonly RecordedDataUseDecision[] = Object.freeze([
  Object.freeze({
    provider: "openai",
    purpose: "reference-edit",
    lineage: "generated-only",
    decision: "allowed",
    evidence: "MEDIA-5 production acceptance (Director, 8bd177cf): generated asset 8494e3ad → OpenAI /v1/images/edits",
  } as const),
]);

export interface DataUseVerdict {
  readonly decision: DataUseDecision;
  /** The evidence of the matching row, or why there is none. Never a secret, never a URL. */
  readonly basis: string;
}

export function decideExternalGenerativeDataUse(
  input: { readonly provider: string; readonly purpose: ExternalGenerativePurpose; readonly lineage: SourceLineage },
  decisions: readonly RecordedDataUseDecision[] = RECORDED_DATA_USE_DECISIONS,
): DataUseVerdict {
  if (input.lineage.status !== "resolved") return { decision: "unknown", basis: "source lineage could not be resolved" };
  const lineage = input.lineage.lineage;
  const row = decisions.find(
    (d) => d.provider === input.provider && d.purpose === input.purpose && d.lineage === lineage,
  );
  if (!row) return { decision: "unknown", basis: "no recorded data-use decision for this provider, purpose and lineage" };
  return { decision: row.decision, basis: row.evidence };
}

/** Only an explicit `allowed` lets bytes leave. `denied` and `unknown` refuse alike. */
export function isExternalGenerativeUseCleared(verdict: DataUseVerdict): boolean {
  return verdict.decision === "allowed";
}
